name: Draft-release
on:
  workflow_dispatch:
 
jobs:

  draft-FF16FontMaker-win:
    runs-on: windows-latest

    steps:
    # setup  
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - uses: microsoft/setup-msbuild@v1.0.2

     # environmental variables
    - run: echo "PROJC=./FF16FontMaker/FF16FontMaker.csproj" >> $env:GITHUB_ENV
    - run: echo "OUTC=./publish/console/" >> $env:GITHUB_ENV
    - run: echo "PROJGUI=./FF16FontMakerGUI/FF16FontMakerGUI.csproj" >> $env:GITHUB_ENV
    - run: echo "OUTGUI=./publish/gui/" >> $env:GITHUB_ENV
    - run: echo "FINALOUT=./publish" >> $env:GITHUB_ENV
    - run: echo "NAME=FF16FontMaker" >> $env:GITHUB_ENV
    - run: echo "REF=${{github.ref}}" >> $env:GITHUB_ENV
    - run: echo "SHA=${{github.sha}}" >> $env:GITHUB_ENV
    - run: echo "MREPO=${{github.repository}}" >> $env:GITHUB_ENV
    
    - name: Get console version
      uses: naminodarie/get-net-sdk-project-versions-action@v1
      id: get-version-cli
      with:
        proj-path: ${{env.PROJC}}
        
    - run: echo "VERSIONC=${{steps.get-version-cli.outputs.assembly-version}}" >> $env:GITHUB_ENV
    
    # Publish console
    - run: msbuild ${{env.PROJGUI}} -t:restore -t:Build -t:Publish /p:PublishDir=".${{env.OUTGUI}}" /p:Configuration=Release /p:SelfContained=False /p:PublishReadyToRun=False /p:PublishTrimmed=False

    - run: echo "GUI=${{env.NAME}}_${{env.VERSIONC}}.zip" >> $env:GITHUB_ENV

    # Create assets
    # create zip
    - run: Get-ChildItem -Path ${{env.OUTGUI}} -Directory | remove-Item -recurse -Force
    - run: Compress-Archive -Path ${{env.OUTGUI}}* -DestinationPath ${{env.FINALOUT}}/${{env.GUI}}


    # RELEASE
    - name: Release
      run: |
          gh release create ${{ env.VERSIONC }} -t "${{env.NAME}} v${{env.VERSIONC}}" -d -F CHANGELOG.md ${{ env.FILES }}
      env:
        FILES: ${{env.FINALOUT}}/${{env.GUI}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
